name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js (v22)
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      # Navigate to the 'backend' directory and verify package-lock.json
      - name: Navigate to Backend and Verify Lock File
        run: |
          cd backend
          if [ ! -f "package-lock.json" ]; then
            echo "Error: package-lock.json not found in backend directory!"
            exit 1
          else
            echo "package-lock.json found"
          fi

      # Install dependencies
      - name: Install Dependencies
        run: |
          cd backend
          npm install

      # Run tests
      - name: Run Tests
        run: |
          cd backend
        # TODO npm run test

      # Deploy to Vercel (optional)
      - name: Deploy to Vercel
        run: |
          cd backend
          npm install -g vercel
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
