name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
    
      # Set up Node.js (using Node.js v22 LTS)
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # Navigate to the 'backend' directory and install dependencies
      - name: Install Dependencies in Backend
        working-directory: backend
        run: |
          npm install

      # Run tests in 'backend' directory
      # - name: Run Tests in Backend
      # working-directory: backend
      # run: |
      # npm test

      # Deploy to Vercel from the 'backend' directory (optional)
      - name: Deploy to Vercel
        working-directory: backend
        run: |
          npm install -g vercel
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm
